#!/usr/bin/env bash
PYTHONPATH=../../src python ../../src/detext/run_detext.py \
--ftr_ext cnn \
--label_column_name label \
--dense_ftrs_column_names wide_ftrs \
--doc_text_column_names doc_title \
--emb_sim_func inner concat diff \
--rescale_dense_ftrs True \
--ltr softmax \
--max_len 32 \
--min_len 3 \
--filter_window_sizes 1 2 3 \
--num_filters 50 \
--num_hidden 100 \
--num_train_steps 10 \
--num_units 60 \
--vocab_hub_url vocab_layer_hub \
--embedding_hub_url embedding_layer_hub \
--nums_dense_ftrs 2 \
--num_sparse_ftrs 100 \
--sparse_emb_size 10 \
--pmetric ndcg@10 \
--all_metrics ndcg@10 precision@1 \
--random_seed 123 \
--steps_per_stats 1 \
--steps_per_eval 2 \
--num_eval_rounds 10 \
--test_batch_size 2 \
--train_batch_size 2 \
--num_hidden 100 \
--explicit_allreduce True \
--learning_rate 0.01 \
--optimizer adamw \
--dev_file sample_data/hc_examples.tfrecord \
--test_file sample_data/hc_examples.tfrecord \
--train_file sample_data/hc_examples.tfrecord \
--vocab_file vocab.txt \
--distribution_strategy one_device \
--num_gpu 0 \
--out_dir /tmp/detext-output/hc_cnn_f50_u32_h100
