# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python 3 application

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.6, 3.7]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python setup.py develop
    - name: Lint with flake8
      run: |
        python -m pip install --upgrade pip
        pip install -U flake8
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --ignore=E121,E123,E226,W292,E402 --max-line-length=160 --exclude=src/detext/model/bert/*.py --show-source --statistics
    - name: Test with pytest
      run: |
        pip install pytest
        pytest

